services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mOsoDfikvmIRsYHqECBcBdbOVQjQPbpU
      POSTGRES_DB: railway
    ports:
      - "5432:5432"

  app:
    build: .
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:mOsoDfikvmIRsYHqECBcBdbOVQjQPbpU@postgres.railway.internal:5432/railway
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    ports:
      - "8081:8081"
    depends_on:
      - postgres
